
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 24 22:05:56 CDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 19;
  public static final int KOPEN = 23;
  public static final int CCERRADO = 6;
  public static final int KCLOSE = 24;
  public static final int THEN = 14;
  public static final int WHILE = 15;
  public static final int POTENCIA = 22;
  public static final int NUMENTERO = 9;
  public static final int IF = 13;
  public static final int DOSP = 4;
  public static final int BASICO = 11;
  public static final int ID = 12;
  public static final int OF = 10;
  public static final int DO = 16;
  public static final int ASIGNACION = 21;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int NUMREAL = 18;
  public static final int error = 1;
  public static final int CABIERTO = 5;
  public static final int INTEGER = 3;
  public static final int PCOMA = 2;
  public static final int OPREL = 17;
  public static final int REAL = 7;
  public static final int ARRAY = 8;
  public static final int OPARIT = 20;
}

